export const Types = {
  RETRIEVE_INITIAL_DATA_REQUEST: 'decks/RETRIEVE_INITIAL_DATA_REQUEST',
  RETRIEVE_DECKS_REQUEST: 'decks/RETRIEVE_DECKS_REQUEST',
  RETRIEVE_DECKS_SUCCESS: 'decks/RETRIEVE_DECKS_SUCCESS',
  ADD_DECK_REQUEST: 'decks/ADD_DECK_REQUEST',
  ADD_DECK_SUCCESS: 'decks/ADD_DECK_SUCCESS',
  DELETE_DECK_REQUEST: 'decks/DELETE_DECK_REQUEST',
  DELETE_DECK_SUCCESS: 'decks/DELETE_DECK_SUCCESS',
  ADD_CARD_REQUEST: 'decks/ADD_CARD_REQUEST',
  ADD_CARD_SUCCESS: 'decks/ADD_CARD_SUCCESS',
  DELETE_CARD_REQUEST: 'decks/DELETE_CARD_REQUEST',
  DELETE_CARD_SUCCESS: 'decks/DELETE_CARD_SUCCESS'
};
